version: '3'

services:
  db:
    image: postgres:15.3
    container_name: my-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=alumno
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=course-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://alumno:123456@db:5432/course-db

  frontend:
    build: ./fronted
    ports:
      - 3001:3000
    depends_on:
      - backend